const initState={
    products:[
        
         {id:42,
          title: "Educational Books",
            subtitle: "",
            authors: "",
            publisher: "",
            image:'42.jpg',
            pageCount: 40, 
            price:60, 
            discount:3, 
            discountPrice:160-3/100 * 60,
           quantity:1, 
            desc:"A List of Educational Books for Private and University Students Also for Use in Public Schools, Grammar Schools, and Middle Class, Elementary, and National Schools",
          
               lang: "en",
            country: "IN",
            categories: "Juvenile Fiction",
            previewLink: "http://books.google.co.in/books?id=_e_WRKnNWuMC&pg=PA40&dq=educationalbooksfor+childrens&hl=&cd=1&source=gbs_api",
           },
         {id:43,
          title: "Jacob's Secret",
          authors: "Emily McLeod",
          publisher: "Independently Published",
            image:'43.jpg',
            pageCount: 600,
            price:26, 
            discount:4, 
            discountPrice:80-4/100 * 80,
           quantity:1, 
            desc: "Once upon a time, there was a town with a beautiful river...But the river was drying, putting every living thing in danger.Little Jacob had a big heart.He was nice to animals, Kind to his family, And helpful to all the people in his little mountain village.The sort of boy who always kept a promise.Until one day, the river almost dried up.If nothing was done, there would be no wáter to drink...And an old man offered to help.But only if Jacob revealed to him a family secret...He'd sworn never to tell. Will Jacob save the town in time?Or is it already too late?",
            lang: "en",
            country: "IN",
            categories: "Juvenile Fiction",
            previewLink: "http://books.google.co.in/books?id=JD8wwQEACAAJ&dq=educationalbooksfor+childrens&hl=&cd=2&source=gbs_api",
           },
         {id:44,
          title: "Be Fearless for Kids",
          subtitle: "Educational Books for Kids",
          authors:    "Tegan Helen",
          publisher: "Createspace Independent Publishing Platform",
            image:'44.jpg',
            pageCount: 96,
            price:160, 
            discount:2, 
            discountPrice:160-2/100 * 160,
           quantity:1, 
            desc:"Incredible book third in a series of books for kids who want big changes and big success. Be fearless for kids teaches kids, techniques and useful tools on how to become fearless, in any situation. helps them grow in self confidence, face challenges head on with no fear, and how to stand in their truth. incredible 7 year old author suitable for kids age 4 - 99",
            lang: "en",
            country: "IN",
            categories:  "Learning",
            previewLink: "http://books.google.co.in/books?id=YgBptAEACAAJ&dq=educationalbooksfor+childrens&hl=&cd=3&source=gbs_api",
           },
      
         {id:45,
          title: "The Power to Unlock Your Dreams",
        "subtitle": "Educational Books for Kids",
          authors:"Tegan Helen",
            publisher: "Createspace Independent Publishing Platform",
            image:'45.jpg',
            pageCount: 92,
            price:40, 
            discount:2, 
            discountPrice:40-2/100 * 40,
           quantity:1, 
            desc: "Tegan Helen is a true inspiration, she had a really challenging start in life but was saved at age three, she has such drive, and is so full of Love! She loves to read and write and hopes to help loads of children, reach their dreams and live a life of happiness, she also believes in giving back as a percentage of each book sold goes to charities close to her heart. Her latest book is based on the law of attraction, broken down in a way all kids will get it and can get out there and reach for the stars! A must read for any kid.",
            lang: "en",
            country: "IN",
            categories:  "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=N0ESMQAACAAJ&dq=educationalbooksfor+childrens&hl=&cd=4&source=gbs_api",
           },
         {id:46,
          title: "Money for Kid's",
          subtitle: "Educational Books for Kids",
          authors: "Tegan Helen",
          publisher: "Createspace Independent Publishing Platform",
            image:'46.jpg',
            pageCount: 76,
            price:50, discount:2, 
            discountPrice:50-2/100 * 50,
           quantity:1, 
            desc:"Children really need to have and read this book lots so they never have to get a job and work. Losing your free time for fun things, to having to go work to get money instead. If you learn everything in this book all about money and what to do with it, and really understand it all. You will never need to work for money and your never to have a Job. Money is everywhere and everything. If we can understand it and learn to control it, you will never have to work for money. Let your money work for you so you can enjoy your life doing the things you enjoy doing. If every kid only learns and does this one thing, we will all be rich no matter what we want to do when we grow up. LET'S FIND OUT MORE.",
            lang: "en",
            country: "IN",
            categories:  "childrens learning",
            previewLink: "http://books.google.co.in/books?id=K9WXDQEACAAJ&dq=educationalbooksfor+childrens&hl=&cd=5&source=gbs_api",
           },
        
         {id:47,
          title: "Now I Eat My ABC's",
          subtitle: "",
            authors:   "Pam Abrams ,Bruce Wolf", 
            publisher: "Cartwheel Books",
            image:'47.jpg',
            pageCount: 8,
            price:40, discount:4, 
            discountPrice:40-4/100 * 440,
           quantity:1, 
            desc:"Babies and toddlers will love the eye-catching photographs of asparagus, blueberries, peas, strawberries, and more in this yummy alphabet book!\"--Cover back.",
            lang: "en",
            country: "IN",
            categories:  "Juvenile Nonfiction",
            previewLink: "http://books.google.co.in/books?id=JDcbHAAACAAJ&dq=educationalbooksfor+childrens&hl=&cd=6&source=gbs_api",
           },
         {d:48,
          title: "Selected List of Educational Books for Secondary Schools",
          subtitle:  "Written Off",
          authors:   "Macmillan & Co",
            publisher: "Crooked Lane Books",
            image:'48.jpg',
            pageCount:776,
            price:680, discount:4, 
            discountPrice:680-4/100 * 680,
           quantity:1, 
            desc:"Rachel Goldman writes mysteries in which Duffy Madison, consultant to the county prosecutor’s office, helps find missing persons. Rachel is busy finishing up her next book, when a man calls out of the blue asking for help in a missing persons case. The caller's name? Duffy Madison. Is this real or has she lost her mind? She doesn't have much time to find out because a serial killer is on the loose, kidnapping and murdering mystery authors. And Rachel may just be the next target. Full of uncanny intrigue and witty humor, E.J. Copperman's imaginative series debut Written Off is sure to be a favorite amongst Copperman's many fans new and old.",
            lang: "en",
            country: "IN",
            categories:  "Textbooks",
            previewLink: "http://books.google.co.in/books?id=5H5IDwAAQBAJ&printsec=frontcover&dq=educationalbooksfor+childrens&hl=&cd=8&source=gbs_api",
           },
         {id:49,
          title: "I Just Want to Do It My Way!",
          subtitle: "",
          publisher: "Boys Town Press",
          authors:  "Julia Cook",
         image:'49.jpg',
         pageCount: 32,
          price:20, 
         discount:2, 
         discountPrice:20-2/100 * 20,
        quantity:1, 
         desc:"RJ is struggling in math class and many of his assignments are missing or incomplet. With help he discovers how to stay organized so he doesn't have to do things over and over again.",
         lang: "en",
         country: "IN",
         categories:  "Self-Help",
         previewLink: "http://books.google.co.in/books?id=5H5IDwAAQBAJ&printsec=frontcover&dq=educationalbooksfor+childrens&hl=&cd=8&source=gbs_api",
        },
         {id:50, 
          title: "Official Gazette of the United States Patent and Trademark Office",
          subtitle: "Trademarks",
         publisher: "Notebook Publishing",
         authors:"",
         image:'50.jpg', 
         pageCount: 320,
         price:240, discount:2, 
         discountPrice:240-2/100 * 240,
         quantity:1, 
         desc:"A fast-paced and harrowing blend of murder mystery, family saga, betrayal and survival. Edge of your seat, with a sharp and jarring conclusion.",
         lang: "en",
         country: "IN",
         categories:   "Trademarks",
         previewLink: "http://books.google.co.in/books?id=LFQbAQAAMAAJ&pg=PA58&dq=educationalbooksfor+childrens&hl=&cd=9&source=gbs_api",
        },
        {id:51, 
          title: "Learning And Educational Books for Toddlers",
          subtitle: "120 Fun Page Coloring Book for Toddlers & Kids Ages 2, 3, 4 & 5 - Activity Book Teaches ABC, Letters & Words for Kindergarten & Preschool Prep Success",
           publisher: "Independently Published",
         authors:"Alphabet Coloring Book For Children",
         image:'51.jpg', 
         pageCount:122,
         price:200, 
         discount:2, 
         discountPrice:200-2/100 * 200,
         quantity:1, 
         desc:"Why you should be buying this book? This book is one of the wonderful coloring books for children that encourage learning, as it contains very important educational elements such as learning numbers and learning alphabets. To become more focused on kids learning new things while also having fun while coloring time! Using colored pencils (or crayons, if you prefer), give your little genius to make this cool coloring. Your child will enjoy learning about all letters, numbers, and colors. This coloring book consists of 120 gallery drawing pages in size 8.5 \"by 11\" This book teaches self-confidence and value. This coloring book is indeed based on studies that show that coloring books are able to fight things like stereotypes, and they are also able to positively influence a child's interest in things like science! This book is designed primarily for children in the age group 3 to 8 years, and this book will provide a wonderful gift for children and also on all occasions and holidays! The book contains a lot of interesting illustrations and strange graphics for all kinds of interesting things like animals and many others, some of which include developing motor skills, stress relief, focus, hand-eye coordination, and much more! This book would make a wonderful gift for any child to help them unlock their full potential! Who knows, maybe one day you will be inspired! When it's time for your kids to go to school, it can be a scary process for both of you. However, it doesn't have to be. With a coloring book like this one, you can prepare for the next school year. Your toddler will enjoy coloring activity, while also learning what it takes to prepare for school. Even just coloring the page daily will help them prepare for the coming new year. Sure, it will be difficult when that day comes, but this coloring book might facilitate the transition. We can benefit from your opinions about this book in the section of reviews. With respect.",
         lang: "en",
         country: "IN",
         categories:   "Kids Learning",
         previewLink: "http://books.google.co.in/books?id=F7RHzQEACAAJ&dq=educationalbooksfor+childrens&hl=&cd=10&source=gbs_api",
        },
        ],
        product:{}
}

const ProductsEducationalReducer =(state= initState, action) => {
   switch(action.type){
       case "PRODUCT":
           return{...state, product: state.products.find(product => product.id === parseInt(action.id))}
       default:
           return state;
   }
}

export default ProductsEducationalReducer;