const initState={
    products:[
        
         {id:32,
            title: "First Class Murder",
            subtitle: "A Murder Most Unladylike Mystery",
            authors: "Robin Stevens",
            publisher: "Penguin UK",
            image:'32.jpg',
            pageCount: 336, 
            price:160, 
            discount:3, 
            discountPrice:160-3/100 * 160,
           quantity:1, 
            desc:"The third instalment in the bestselling Murder Most Unladylike series; just like the iconic Agatha Christie, Hazel and Daisy have boarded the Orient Express! ----- 'A delight . . . Hazel and Daisy are aboard the Orient Express: cue spies, priceless jewels, a murder and seriously upgraded bun breaks' The Bookseller 'Addictive . . . A rumbustious reworking of Agatha Christie's Orient Express caper' New Statesman ----- Daisy Wells and Hazel Wong are taking a holiday on the world-famous Orient Express - and it's clear that each of their fellow first-class passengers has something to hide. Even more intriguing: there is rumour of a spy in their midst. Then, during dinner, there is a scream from inside one of the cabins. When the door is broken down, a passenger is found murdered, her stunning ruby necklace gone. But the killer has vanished - as if into thin air. Daisy and Hazel are faced with their first ever locked-room mystery - and with competition from several other sleuths, who are just as determined to crack the case.",
            lang: "en",
            country: "IN",
            categories: "Juvenile Fiction",
            previewLink: "http://books.google.co.in/books?id=P7p1CwAAQBAJ&printsec=frontcover&dq=detective+and+mystry&hl=&cd=1&source=gbs_api",
           },
         {id:33,
            title: "The Detective",
          authors: "Roderick Thorp",
          publisher: "Open Road Media",
            image:'33.jpg',
            pageCount: 600,
            price:560, 
            discount:4, 
            discountPrice:560-4/100 * 560,
           quantity:1, 
            desc: "In this bestselling book that inspired the hit movie by the same name, starring Frank Sinatra, an apparent suicide forces a PI to reconsider his most famous case Joe Leland returned from World War II with a chest full of medals, but his greatest honor came after he traded his pilot’s wings for a detective’s shield. Catching the Leikman killer made Joe a local hero, but the shine quickly wore off, and it wasn’t long before he left the police force to start his own private agency. Years after his greatest triumph, Joe has a modest income and a quiet life—both of which may soon fall apart. When Colin MacIver dies at the local racetrack, the coroner rules that he took his own life, but his widow knows better. Because MacIver’s life insurance policy doesn’t cover suicide, his wife is left broke, desperate, and afraid for her safety. She hires Leland to find out who could have killed her gentle, unassuming husband—a simple question that will turn this humble city inside out.",
            lang: "en",
            country: "IN",
            categories: "Fiction",
            previewLink: "http://books.google.co.in/books?id=ZBTNBAAAQBAJ&printsec=frontcover&dq=detective+and+mystry&hl=&cd=2&source=gbs_api",
           },
         {id:34,
            title: "New Perspectives on Detective Fiction",
            subtitle: "Mystery Magnified",
          authors:    "Casey Cothran , Mercy Cannon",
          publisher: "Routledge",
            image:'34.jpg',
            pageCount: 250,
            price:160, 
            discount:2, 
            discountPrice:160-2/100 * 160,
           quantity:1, 
            desc:"This collection establishes new perspectives on the idea of mystery, as it is enacted and encoded in the genre of detective fiction. Essays reclaim detective fiction as an object of critical inquiry, examining the ways it shapes issues of social destabilization, moral ambiguity, reader complicity, intertextuality, and metafiction. Breaking new ground by moving beyond the critical preoccupation with classification of historical types and generic determinants, contributors examine the effect of mystery on literary forms and on readers, who experience the provocative, complex process of coming to grips with the unknown and the unknowable. This volume opens up discussion on publically acclaimed, modern works of mystery and on classic pieces, addressing a variety of forms including novels, plays, graphic novels, television series, films, and ipad games. Re-examining the interpretive potential of a genre that seems easily defined yet has endless permutations, the book closely analyzes the cultural function of mystery, the way it intervenes in social and political problems, as well as the literary properties that give the genre its particular shape. The volume treats various texts as meaningful subjects for critical analysis and sheds new light on the interpretive potential for a genre that creates as much ambiguity as it does clarity. Scholars of mystery and detective fiction, crime fiction, genre studies, and cultural studies will find this volume invaluable.",
            lang: "en",
            country: "IN",
            categories:  "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=MIe9CgAAQBAJ&printsec=frontcover&dq=detective+and+mystry&hl=&cd=3&source=gbs_api",
           },
      
         {id:35,
          title:  "Detective Fiction and the Problem of Knowledge",
           subtitle: "An Action Adventure",
          authors:"Antoine Dechêne",
            publisher: "Springer",
            image:'35.jpg',
            pageCount: 347,
            price:40, 
            discount:3, 
            discountPrice:40-3/100 * 40,
           quantity:1, 
            desc: "This book establishes the genealogy of a subgenre of crime fiction that Antoine Dechêne calls the metacognitive mystery tale. It delineates a corpus of texts presenting 'unreadable' mysteries which, under the deceptively monolithic appearance of subverting traditional detective story conventions, offer a multiplicity of motifs – the overwhelming presence of chance, the unfulfilled quest for knowledge, the urban stroller lost in a labyrinthine text – that generate a vast array of epistemological and ontological uncertainties. Analysing the works of a wide variety of authors, including Edgar Allan Poe, Jorge Luis Borges, and Henry James, this book is vital reading for scholars of detective fiction.",
            lang: "en",
            country: "IN",
            categories:  "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=-TppDwAAQBAJ&printsec=frontcover&dq=detective+and+mystry&hl=&cd=4&source=gbs_api",
           },
         {id:36,
            title: "Whose Body?",
          subtitle: "",
          authors: "Dorothy L. Sayers",
          publisher: "Courier Corporation",
            image:'36.jpg',
            pageCount: 84,
            price:50, discount:2, 
            discountPrice:50-2/100 * 50,
           quantity:1, 
            desc:"There's a dead body in his bathtub, wearing nothing but a pair of pince-nez spectacles. Enter Lord Peter Wimsey, the original gentleman sleuth, who debuted in this 1923 novel.",
            lang: "en",
            country: "IN",
            categories:  "Fiction",
            previewLink: "http://books.google.co.in/books?id=tDmhBgAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=6&source=gbs_api",
           },
        
         {id:37,
          title: "The Street Lawyer",
          subtitle: "A History",
            authors:  "John Grisham",
            
            publisher: "Random House",
            image:'37.jpg',
            pageCount: 368,
            price:440, discount:4, 
            discountPrice:440-4/100 * 440,
           quantity:1, 
            desc: "_______________________________________ Michael Brock is a man in the fast lane. He's a rising star at Drake & Sweeney, a giant Washington law firm. No time to waste, no time to toss a few coins to beggars. No time for a conscience. Until the day a man takes several lawyers hostage at his firm, shouting about an eviction. Police snipers shoot the hostage taker dead, but Brock feels compelled to investigate. What he discovers is a shocking violation of the rights of the homeless on the city streets, with Drake & Sweeney up to its neck in it, and suddenly his conscience begins to stir. But to do the right thing, he might have to steal his own firm's secrets... _______________________________________ ‘A master at the art of deft characterisation and the skilful delivery of hair-raising crescendos' – Irish Independent 'John Grisham is the master of legal fiction' – Jodi Picoult 'The best thriller writer alive' – Ken Follett ‘John Grisham has perfected the art of cooking up convincing, fast-paced thrillers’ – Telegraph ‘Grisham is a superb, instinctive storyteller’ – The Times ‘Grisham's storytelling genius reminds us that when it comes to legal drama, the master is in a league of his own.’ – Daily Record ‘Masterful – when Grisham gets in the courtroom he lets rip, drawing scenes so real they're not just alive, they're pulsating’ – Mirror ‘A giant of the thriller genre’ – TimeOut",
            lang: "en",
            country: "IN",
            categories:  "PerfLiterary Criticism",
            previewLink: "ttp://books.google.co.in/books?id=VAuF-A4OdesC&printsec=frontcover&dq=detective+and+mystry&hl=&cd=6&source=gbs_api",
           },
         {d:38,
            title: "Written Off",
          subtitle:  "Written Off",
          authors:   "E. J. Copperman",
            publisher: "Crooked Lane Books",
            image:'38.jpg',
            pageCount: 336,
            price:380, discount:4, 
            discountPrice:380-4/100 * 380,
           quantity:1, 
            desc:"Rachel Goldman writes mysteries in which Duffy Madison, consultant to the county prosecutor’s office, helps find missing persons. Rachel is busy finishing up her next book, when a man calls out of the blue asking for help in a missing persons case. The caller's name? Duffy Madison. Is this real or has she lost her mind? She doesn't have much time to find out because a serial killer is on the loose, kidnapping and murdering mystery authors. And Rachel may just be the next target. Full of uncanny intrigue and witty humor, E.J. Copperman's imaginative series debut Written Off is sure to be a favorite amongst Copperman's many fans new and old.",
            lang: "en",
            country: "IN",
            categories:  "Social Science",
            previewLink: "http://books.google.co.in/books?id=wCQjDAAAQBAJ&printsec=frontcover&dq=detective+and+mystry&hl=&cd=7&source=gbs_api",
           },
         {id:39,
            title: "The Deep Blue Good-By",
          subtitle: "Mystry",
          publisher: "Random House Incorporated",
          authors:  "John Dann MacDonald",
         image:'39.jpg',
         pageCount: 222,
          price:120, 
         discount:3, 
         discountPrice:120-3/100 * 120,
        quantity:1, 
         desc:"He's a self-described beach bum who won his houseboat in a card game. He's also a knight errant who's wary of credit cards, retirement benefits, political parties, mortgages, and television. He only works when his cash runs out and his rule is simple: he'll help you find whatever was taken from you, as long as he can keep half....",
         lang: "en",
         country: "IN",
         categories:  "Fiction",
         previewLink: "http://books.google.co.in/books?id=m1YFEAAAQBAJ&dq=action+and+adventure&hl=&cd=9&source=gbs_api",
        },
         {id:40, 
            title: "The Dime Box",
          subtitle: "The Dime Box",
         publisher: "Notebook Publishing",
         authors:"Karen Grose",
         image:'40.jpg', 
         pageCount: 320,
         price:240, discount:2, 
         discountPrice:240-2/100 * 240,
         quantity:1, 
         desc:"A fast-paced and harrowing blend of murder mystery, family saga, betrayal and survival. Edge of your seat, with a sharp and jarring conclusion.",
         lang: "en",
         country: "IN",
         categories:   "Fiction",
         previewLink: "http://books.google.co.in/books?id=DscAywEACAAJ&dq=detective+and+mystry&hl=&cd=9&source=gbs_api",
        },
        {id:41, 
            title: "Library of the World's Best Mystery and Detective Stories",
       subtitle: "Mystery and Detective Stories",
         publisher: "",
         authors:"Julian Hawthorne",
         image:'41.jpg', 
         pageCount:304,
         price:200, 
         discount:2, 
         discountPrice:200-2/100 * 200,
         quantity:1, 
         desc:"This book has been considered by academicians and scholars of great significance and value to literature. This forms a part of the knowledge base for future generations. So that the book is never forgotten we have represented this book in a print format as the same form as it was originally first published. Hence any marks or annotations seen are left intentionally to preserve its true nature.",
         lang: "en",
         country: "IN",
         categories:   "Mystery and Detective Stories",
         previewLink: "http://books.google.co.in/books?id=IS8EzgEACAAJ&dq=detective+and+mystry&hl=&cd=10&source=gbs_api",
        },
        ],
        product:{}
}

const ProductsDetectiveReducer =(state= initState, action) => {
   switch(action.type){
       case "PRODUCT":
           return{...state, product: state.products.find(product => product.id === parseInt(action.id))}
       default:
           return state;
   }
}

export default ProductsDetectiveReducer;