const initState={
    products:[
        
         {id:11,
          title: "The Beginners Guide To Action and Adventure Games",
            authors: "Cora Pollard",
            publisher: "IMU Ventures Publishing",
            image:'11.jpg',
            pageCount: 184, 
            price:160, 
            discount:3, 
            discountPrice:160-3/100 * 160,
           quantity:1, 
            desc: "The genres of video games had categorized the game on its own mechanics including other details. Among these video game genres or categories, there are 2 well known genres that are most discussed. These are the Role Playing games and Action/Adventure games. They were around for a long period of time. Each of them has been working on game and plot mechanics, along with one’s respective strength. But this time, people are becoming more indulged with adventure games. There are various aspects surrounding this subject and it is time to have a clear understanding about the reason behind other persons’ great fascination and involvement in this genre. Get all the info you need here. Let Us Know What You Think!",
            lang: "en",
            country: "IN",
            categories: "Games",
            previewLink: "http://books.google.co.in/books?id=vFZLCgAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=2&source=gbs_api",
           },
         {id:12,
          title: "Action and Adventure Cinema",
          authors: "Yvonne Tasker",
          publisher: "Presbyterian Publishing Corp",
            image:'12.jpg',
            pageCount: 414,
            price:260, 
            discount:4, 
            discountPrice:260-4/100 * 260,
           quantity:1, 
            desc: "Addressing areas such as genre, film history and style, action and spectacle, stars and bodies, action auteurs and the film industry, the reader covers both Hollywood and also European and Asian action cinema.",
            lang: "en",
            country: "IN",
            categories: "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=JfG2TCQlyhIC&dq=action+and+adventure&hl=&cd=3&source=gbs_api",
           },
         {id:13,
          title: "India Was One",
          authors:   "An Indian" ,
          publisher: "Season Ball",
            image:'13.jpg',
            pageCount: 368,
            price:60, 
            discount:2, 
            discountPrice:160-2/100 * 160,
           quantity:1, 
            desc:"...Suddenly, he saw something shiny at the bottom of the abyss. He squinted his eyes to see what it was. He ran back to his binoculars and turned them to see what it was. Sharp barbed wires that separated the two mountains came into focus. He had come as far as he could in his country. But she was standing in another country. He was in South India and she was in North India... Have you ever imagined India being divided into two countries? What happens to the millions of Indians who are from South India but are now residing in North India? Kaahi & Jai were two such people who got trapped in this situation. Everything was going smoothly for them and suddenly, their world turned upside down. How will they get together? Will India become one again? Take an exciting journey with them from their college days in Mumbai to their life in the US and back to India when they find out that India is divided. IndiaWasOne.com",
            lang: "en",
            country: "IN",
            categories:  "Fiction",
            previewLink: "http://books.google.co.in/books?id=1Q9mjwEACAAJ&dq=action+and+adventure&hl=&cd=5&source=gbs_api",
           },
      
         {id:14,
          title: "A Sinking Feeling",
          subtitle: "An Action Adventure",
            publisher: "Christian Burch",
            image:'14.jpg',
            pageCount: 88,
            price:40, 
            discount:3, 
            discountPrice:40-3/100 * 40,
           quantity:1, 
            desc:"From the author of E.V.I.L., Dark Horizons, Snapshot, and the bestseller Haunted, comes a new adventure series sure to enthrall and entertain all ages. A Sinking Feeling is the first entry in the Trailblazers saga, following a set of twins who go on crazy, fun, and dangerous adventures through time as Trailblazers. Twins Connor and Emily Rose are finally turning the big thirteen. Their grandfather has always doted on them each year and this birthday, their expectations are high. The gift he gives them is one that will change their lives forever. Not understanding why their grandfather has given them a coin, they're naturally disappointed... He assures them that they will understand how special the coin is soon enough. Adventures await, he promises, but urges them to wait until he returns to use the coin. Not understanding, they only nod their head, still upset by the seemingly lame gift. Until the next afternoon, when Connor flips the coin and their world turns upside down as they are transported back through time and find themselves aboard the doomed ship, The Titanic. Cold, scared, and worried, they realize why the coin is so special. While trying to figure out how it was possible, the ship hits the iceberg. The burden falls to their grandfather, John, to follow them and rescue them before the ship sinks to the depths, with them still aboard",
            lang: "en",
            country: "IN",
            categories:  "Action Adventure",
            previewLink: "http://books.google.co.in/books?id=Az5dE4nyznsC&pg=PA47&dq=horror&hl=&cd=4&source=gbs_api",
           },
         {id:15,
          title: "Outdoor Action and Adventure Photography",
          subtitle: "Action and Adventure Photography",
          authors: "Dan Bailey",
          publisher: "CRC Press",
            image:'15.jpg',
            pageCount: 312,
            price:150, discount:2, 
            discountPrice:150-2/100 * 150,
           quantity:1, 
            desc:"The difference between getting the shot and missing the shot comes down to split seconds and how you manage your gear and your technique. In Outdoor Action and Adventure Photography professional adventure sports photographer Dan Bailey shows readers how to react quickly to unfolding scenes and anticipate how the subject and the background might converge. Capturing those significant moments to produce powerful imagery that evoke the feel and mood of adventure requires specialized skills and a wide variety of creative ideas. This book teaches photographers how to think geometrically and how to pull together the elements that make for a successful shot, all while being immersed in the action. The practical manual will improve your technique for creating more compelling adventure imagery, whether you’re shooting ultra-marathoners splattered in mud, rock climbers in a crevasse, or mountain bikers hurtling past you. In this book, you’ll: • Discover the necessary equipment for shooting action, learn how to use it to its full potential, and develop a comprehensive adventure photography camera system that you can adapt to different shooting situations. • Learn specific techniques and creative ideas that help you freeze the moment and create images that convey excitement, mood, and the feel of adventure. • Learn advanced skills that can help you start defining your own particular style of action photography and create a \"brand\" of photography that’s based around your passion and your vision. • Examine case studies that break down the process for shooting different types of action subjects and see the nuts and bolts of how to create powerful imagery from start to finish.",
            lang: "en",
            country: "IN",
            categories:  "Photography",
            previewLink: "http://books.google.co.in/books?id=tDmhBgAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=6&source=gbs_api",
           },
        
         {id:17,
          title: "Paramilitary Action-Adventure Fiction",
          subtitle: "A History",
            authors:  "ader Elhefnawy",
            
            publisher: "Nader Elhefnawy",
            image:'17.jpg',
            pageCount: 229,
            price:140, discount:4, 
            discountPrice:140-4/100 * 140,
           quantity:1, 
            desc:"We are all familiar with the idea of the action hero as a latterday avenger with a gun—Dirty Harry, Chuck Norris' screen heroes, Rambo. Yet, how did the idea of such heroes emerge in the first place? Why did it explode as it did in the 1970s and, still more, the 1980s, defining the Hollywood action films of that decade? And why did it fall out of fashion? PARAMILITARY ACTION-ADVENTURE FICTION: A HISTORY examines all these questions, and much more, as it traces the rise of paramilitary action heroes in the tensions and fears underlying the civil image of the nineteenth century, through the stresses of the world wars and the Cold War, to the emergence by the 1960s of commandos fighting undeclared wars on the streets of urban America—and the evolution of that image in the half century since.",
            lang: "en",
            country: "IN",
            categories:  "PerfLiterary Criticism",
            previewLink: "http://books.google.co.in/books?id=u8_SDwAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=7&source=gbs_api",
           },
         {d:18,
          title: "Action Figures",
          subtitle: "Men, Action Films, and Contemporary Adventure Narratives",
          authors:   "M. Gallagher",
            publisher: "Springer",
            image:'18.jpg',
            pageCount: 234,
            price:180, discount:4, 
            discountPrice:120-4/100 * 120,
           quantity:1, 
            desc:"What accounts for the massive global popularity of action films and adventure literature? How do men and women respond to iconic screen stars such as Jackie Chan, Arnold Schwarzenegger, Steve McQueen, and Charlton Heston? Action genres have been Hollywood's most profitable global exports for most of its history, their male heroes the subject of much fascination and derision. Bestselling literary thrillers, from The Hunt for Red October to Into Thin Air , have also contributed markedly to popular understandings of male activity. Action Figures takes stock of action narratives' many appeals and recognizes how contemporary crises of gender identity manifest themselves in popular commercial texts.",
            lang: "en",
            country: "IN",
            categories:  "Social Science",
            previewLink: "http://books.google.co.in/books?id=3WnIAAAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=8&source=gbs_api",
           },
         {id:19,
          title: "Action Adventure",
          subtitle: "Action",
          publisher: "Lulu Press, Inc",
          authors:  "Kathiravan RK",
         image:'19.jpg',
         pageCount: 183,
          price:120, 
         discount:3, 
         discountPrice:120-3/100 * 120,
        quantity:1, 
         desc:'This ebook inside you know about the Action Adventure games, and games of puzzle games and many adventure games and action',
         lang: "en",
         country: "IN",
         categories:  "Fiction",
         previewLink: "http://books.google.co.in/books?id=m1YFEAAAQBAJ&dq=action+and+adventure&hl=&cd=9&source=gbs_api",
        },
         {id:20, 
          title: "The Oath of the Vayuputras",
          subtitle: "The Shiva Trilogy",
         publisher: "Hachette UK",
         authors:"Amish Tripathi",
         image:'20.jpg', 
         pageCount: 320,
         price:140, discount:2, 
         discountPrice:140-2/100 * 140,
         quantity:1, 
         desc:'Shiva has accepted his destiny, but it has brought him to despair. Can he heal himself and the people who look to him as a god? Today, Shiva is a god. But four thousand years ago, he was just a man - until he brought his people to Meluha, a near-perfect empire founded by the great king Lord Ram. There he realised he was the Neelkanth, a barbarian long prophesied to be Meluhas saviour. But in his hour of victory fighting the Chandravanshis Meluhas enemy he discovered they had their own prophecy. Now he must fight to uncover the treachery within his inner circle, and unmask those who are about to destroy all that he has fought for. Shiva is about to learn that good and evil are two sides of the same coin . . .',
         lang: "en",
         country: "IN",
         categories:   "Fiction",
         previewLink: "http://books.google.co.in/books?id=ZO9gBQAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=10&source=gbs_api",
        },
        {id:21, 
          title: "The Action and Adventure Cinema",
          subtitle: "Action and Adventure ",
         publisher: "Routledge",
         authors:"Yvonne Tasker",
         image:'21.jpg', 
         pageCount: 432,
         price:280, discount:2, 
         discountPrice:280-2/100 * 140,
         quantity:1, 
         desc:"This exciting collection addresses action and adventure from the silent to the contemporary period exploring diverse questions of aesthetics, industry and ideology. Action has established itself as one of the leading commercial genres of the New Hollywood cinema, generating extensive debate in the process. Contributors consider how action might best be defined, how it has developed historically, and how it works formally. The critical reception and standing of action and adventure cinema is considered in relation to questions of national culture, violence and the 'art' of cinema. Themes explored include genre and definitions; early action, sensation and melodrama; authorship and action; national and transnational action-adventure traditions; action aesthetics; spectacle and narrative; stars and bodies; class; gender; race and ethnicity. Attempting to evaluate the significance of this type of filmmaking for both popular cinema and film studies, the book underlines the central place of action and adventure within film history.",
         lang: "en",
         country: "IN",
         categories:   "Performing Arts",
         previewLink: "http://books.google.co.in/books?id=hZqBAgAAQBAJ&printsec=frontcover&dq=action+and+adventure&hl=&cd=1&source=gbs_api",
        },
        ],
        product:{}
}

const ProductsActionReducer =(state= initState, action) => {
   switch(action.type){
       case "PRODUCT":
           return{...state, product: state.products.find(product => product.id === parseInt(action.id))}
       default:
           return state;
   }
}

export default ProductsActionReducer;