const initState={
    products:[
        
         {id:22,
            title: "A Complete History of American Comic Books",
            authors: "Shirrel Rhoades",
            publisher: "peter Lang",
            image:'22.jpg',
            pageCount:353, 
            price:260, 
            discount:3, 
            discountPrice:260-3/100 * 260,
           quantity:1, 
            desc: "This book is an updated history of the American comic book by an industry insider. You'll follow the development of comics from the first appearance of the comic book format in the Platinum Age of the 1930s to the creation of the superhero genre in the Golden Age, to the current period, where comics flourish as graphic novels and blockbuster movies. Along the way you will meet the hustlers, hucksters, hacks, and visionaries who made the American comic book what it is today. It's an exciting journey, filled with mutants, changelings, atomized scientists, gamma-ray accidents, and supernaturally empowered heroes and villains who challenge the imagination and spark the secret identities lurking within us.",
            lang: "en",
            country: "IN",
            categories: "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=O16BXbITZwEC&printsec=frontcover&dq=comicbooks&hl=&cd=1&source=gbs_api",
           },
         {id:23,
            title: "Reading Comics",
            subtitle: "Language, Culture, and the Concept of the Superhero in Comic Books",
          authors: "Mila Bongco",
          publisher: "Routledge",
            image:'23.jpg',
            pageCount:  238,
            price:260, 
            discount:2, 
            discountPrice:260-2/100 * 260,
           quantity:1, 
            desc: "First published in 2000. Routledge is an imprint of Taylor & Francis, an informa company.",   
              lang: "en",
            country: "IN",
            categories: "History",
            previewLink: "http://books.google.co.in/books?id=Z5VIAwAAQBAJ&pg=PT48&dq=comicbooks&hl=&cd=2&source=gbs_api",
           },
         {id:24,
            title: "Comic Books",
        subtitle: "How the Industry Works",
          authors:   "Shirrel Rhoades" ,
          publisher: "Peter Lang",
            image:'24.jpg',
            pageCount: 406,
            price:360, 
            discount:2, 
            discountPrice:360-2/100 * 360,
           quantity:1, 
            desc:"This book is an insider's guide to how the comic book industry works. You'll learn how comic book superheroes are created and the deeper meanings they represent. You'll follow the development of sequential art storytelling - from caveman wall paintings to modern manga and cinematic techniques. Here you will explore comics in all forms: those flimsy pamphlets we call comic books; thick graphic novels; Japanese manga; and blockbuster movies featuring epic battles between good and evil. But behind it all, you'll discover how comics are an intellectual property business, the real money found in licensed bedsheets and fast-food merchandise, heart-pounding theme park rides and collectible toys, video games, and Hollywood extravaganza featuring such popular superheroes as Spider-Man, Superman, X-Men, and Batman.",
            lang: "en",
            country: "IN",
            categories:  "Social Science",
            previewLink: "http://books.google.co.in/books?id=wSL7mS6mpmkC&pg=PA33&dq=horror&hl=&cd=3&source=gbs_api",
           },
      
         {id:25,
            title: "Comic Books and Juvenile Deliquency",
            subtitle: "Interim Report Pursuant to S. Res. 89, 83d Cong., 1st Sess., and S. 190, 83d Cong., 2d Sess., a Part of the Investigation of Juvenile Delquency in the United States",
          publisher: "Psychology Press",
            image:'25.jpg',
            pageCount: 50,
            price:40, 
            discount:2, 
            discountPrice:40-2/100 * 40,
           quantity:1, 
            desc:'',  lang: "en",
            country: "IN",
            categories:  "Comic books and children",
            previewLink: "http://books.google.co.in/books?id=nGxxtfPmS-IC&pg=PA20&dq=comicbooks&hl=&cd=4&source=gbs_api",
           },
         {id:26,
            title: "Comic Books Incorporated",
            subtitle: "How the Business of Comics Became the Business of Hollywood",
          authors: "Shawna Kidman",
          publisher: "University of California Press",
            image:'26.jpg',
            pageCount: 328,
            price:190, discount:2, 
            discountPrice:190-2/100 * 190,
           quantity:1, 
            desc:'This is a series of introductory books about different types of writing. One strand of the series focuses on genres such asScience Fiction, Horror, Romance, and Crime, and the other focuses on movements or styles often associated with historicaland cultural locations—Postcolonial, Native American, Scottish, Irish, American Gothic.Authors covered in this volume includeWilliam Peter Blatty, Ira Levine, BramStoker, Shirley Jackson, Angela Carter,Mary Shelley, Stephen King, Anne Rice,and Washington Irving.',
            lang: "en",
            country: "IN",
            categories:  "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=PD1CZfa5wicC&pg=PA159&dq=horror&hl=&cd=6&source=gbs_api",
           },
         {id:27,
            title: "Comic Books as History",
        subtitle: "The Narrative Art of Jack Jackson, Art Spiegelman, and Harvey Pekar",
          authors:  "Joseph Witek",
          publisher: "Univ. Press of Mississippi",
            image:'27.jpg',
            pageCount: 164,
            price:80, discount:2, 
            discountPrice:80-2/100 * 80,
           quantity:1, 
            desc:'Describes changing public attitudes towards comic books',
            lang: "en",
            country: "IN",
            categories:  "Antiques & Collectibles",
            previewLink: "http://books.google.co.in/books?id=XKhgy4xU5e8C&printsec=frontcover&dq=comicbooks&hl=&cd=6&source=gbs_api",
           },
         {id:28,
            title: "Comic Books",
            subtitle: "From Superheroes to Manga",
            authors:  "Joshua Hatch",
            
            publisher: "Capstone Classroom",
            image:'28.jpg',
            pageCount: 48,
            price:40, discount:2, 
            discountPrice:40-2/100 * 40,
           quantity:1, 
            desc:"Describes the history of comic books and graphic novels, and discusses various superheroes, including Superman, Spider-Man, and the Fantastic Four.",
      
            lang: "en",
            country: "IN",
            categories:  "Juvenile Nonfiction",
            previewLink: "http://books.google.co.in/books?id=2MSxeZeq920C&printsec=frontcover&dq=comicbooks&hl=&cd=7&source=gbs_api",
           },
         {id:29,
            title: "Comic Books and Comic Art",
            subtitle: "Essays in Popular Americana",
        subtitle: "Auction, Wednesday, December 18 1991",
          authors:   "Gary Don Rhodes",
          
          publisher: "McFarland",
            image:'29.jpg',
            pageCount: 306,
            price:180, discount:4, 
            discountPrice:180-4/100 * 180,
           quantity:1, 
            desc:'Drive-in movie theaters and the horror films shown at them during the 1950s, 60s, and early 70s may be somewhat outdated, but they continue to enthrall movie buffs today. More than just fodder for the satirical cannons of Joe Bob Briggs and Mystery Science Theatre 3000, they appeal to knowledgeable fans and film scholars who understand their influence on American popular culture. This book is a collection of eighteen essays by various scholars on the classic drive-in horror film experience. Those in Section One emphasize the roles of the drive-in theater in the United States--and its cultural cousin, Australia. Section Two examines how horror operated at the drive-in, the rhetoric used in coming attraction trailers, horror film premieres at drive-ins, double features, and the preproduction, production, and marketing of Last House on the Left. Section Three addresses the effects of the Vietnam War and counter-culture on The Texas Chainsaw Massacre, and the Cold War on Cat Women of the Moon. Section Four explores gender issues and sexuality, two of the most common and most important subjects of horror film analysis. Section Five covers drive-in culture via Hush...Hush, Sweet Charlotte, 2000 Maniacs, and the films of Mario Bava. Section Six investigates a variety of issues, such as the drive-in horror films embrace of DNA, the use of cinematic form to create a non-Hollywood look in Wizard of Gore, and the many different prints and running times of I Drink Your Blood.' ,
            lang: "en",
            country: "IN",
            categories:  "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=4Qj9xgEACAAJ&dq=comicbooks&hl=&cd=8&source=gbs_api",
           },
         {id:30,
            title: "Disability in Comic Books and Graphic Narratives",
          subtitle: "Comic Books",
          authors:  "Zach Whalen",
          publisher: "Springer",
         image:'30.jpg',
         pageCount: 216,
          price:120, 
         discount:3, 
         discountPrice:160-3/100 * 160,
        quantity:1, 
         desc: "As there has yet to be any substantial scrutiny of the complex confluences a more sustained dialogue between disability studies and comics studies might suggest, Disability in Comic Books and Graphic Narratives aims through its broad range of approaches and focus points to explore this exciting subject in productive and provocative ways.",
        
         lang: "en",
         country: "IN",
         categories:  "Literary Criticism",
         previewLink: "http://books.google.co.in/books?id=3rTtCwAAQBAJ&printsec=frontcover&dq=comicbooks&hl=&cd=9&source=gbs_api",
        },
         {id:31, title:'Library of Congress Subject Headings ', 
         subtitle: "Library of Congress Subject Headings", 
         publisher: "Library of Congress",
         authors:"Jack Marlon",
         image:'31.jpg', 
         pageCount: 173,
         price:100, discount:3, 
         discountPrice:120-3/100 * 100,
         quantity:1, 
         desc:'',   
          lang: "en",
         country: "IN",
         categories:  "Subject headings, Library of Congress",
         previewLink: "http://books.google.co.in/books?id=y2UfnAyWoHwC&pg=PA1667&dq=comicbooks&hl=&cd=10&source=gbs_api",
        },

        ],
        product:{}
}

const ProductsComicReducer =(state= initState, action) => {
   switch(action.type){
       case "PRODUCT":
           return{...state, product: state.products.find(product => product.id === parseInt(action.id))}
       default:
           return state;
   }
}

export default ProductsComicReducer;