const initState={
    products:[
        
         {id:1,
            title: "Horror International",
            authors: "Steven Jay Schneider & Tony Williams",
            publisher: "Wayne State University Press",
            image:'1.jpg',
            pageCount: 384, 
            price:260, 
            discount:3, 
            discountPrice:260-3/100 * 260,
           quantity:1, 
            desc: 'A close look at horror films from around the world, drawing attention to neglected social, cultural, and ideological aspects of the horror genre in international cinema.',
            lang: "en",
            country: "IN",
            categories: "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=nGXb4ahiuZMC&pg=PA141&dq=horror&hl=&cd=1&source=gbs_api",
           },
         {id:2,
            title: "The Horror Film",
          authors: "Stephen Prince",
          publisher: "Rutgers University Press",
            image:'2.jpg',
            pageCount: 272,
            price:160, 
            discount:2, 
            discountPrice:160-2/100 * 160,
           quantity:1, 
            desc: 'In this volume, Stephen Prince has collected essays reviewing the history of the horror film and the psychological reasons for its persistent appeal, as well as discussions of the developmental responses of young adult viewers and children to the genre. The book focuses on recent postmodern examples such as The Blair Witch Project. In a daring move, the volume also examines Holocaust films in relation to horror. Part One features essays on the silent and classical Hollywood eras. Part Two covers the postWorld War II era and discusses the historical, aesthetic, and psychological characteristics of contemporary horror films. In contrast to horror during the classical Hollywood period, contemporary horror features more graphic and prolonged visualizations of disturbing and horrific imagery, as well as other distinguishing characteristics. Princes introduction provides an overview of the genre, contextualizing the readings that follow. Stephen Prince is professor of communications at Virginia Tech. He has written many film books, including Classical Film Violence: Designing and Regulating Brutality in Hollywood Cinema, 19301968, and has edited Screening Violence, also in the Depth of Field Series.',
            lang: "en",
            country: "IN",
            categories: "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=S6jKVfuQG3wC&pg=PA131&dq=horror&hl=&cd=2&source=gbs_api",
           },
         {id:3,
            title: "The Pleasures of Horror",
          authors:   "Matt Hills" ,
          publisher: "A&C Black",
            image:'3.jpg',
            pageCount: 250,
            price:60, 
            discount:2, 
            discountPrice:60-2/100 * 60,
           quantity:1, 
            desc:'Pleasures of Horror is a stimulating and insightful exploration of horror fictions—literary, cinematic and televisual—and the emotions they engender in their audiences. The text is divided into three sections. The first examines how horror is valued and devalued in different cultural fields; the second investigates the cultural politics of the contemporary horror film; while the final part considers horror fandom in relation to its embodied practices (film festivals), its \"reading formations\" (commercial fan magazines and fanzines) and the role of special effects. Pleasures of Horror combines a wide range of media and textual examples with highly detailed and closely focused exposition of theory. It is a fascinating and engaging look at responses to a hugely popular genre and an invaluable resource for students of media, cultural and film studies and fans of horror.',
            lang: "en",
            country: "IN",
            categories:  "Social Science",
            previewLink: "http://books.google.co.in/books?id=wSL7mS6mpmkC&pg=PA33&dq=horror&hl=&cd=3&source=gbs_api",
           },
      
         {id:4,
            title: "Horror, the Film Reader",
            authors:   "Mark Jancovich",
            publisher: "Psychology Press",
            image:'4.jpg',
            pageCount: 188,
            price:60, 
            discount:2, 
            discountPrice:60-2/100 * 60,
           quantity:1, 
            desc:'Key articles and essays introduce students to debates over the definition of the horror film as a genre, its sexual politics, and its conditions of production and consumption.',
            lang: "en",
            country: "IN",
            categories:  "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=Az5dE4nyznsC&pg=PA47&dq=horror&hl=&cd=4&source=gbs_api",
           },
         {id:5,
            title: "Horror Fiction",
          subtitle: "An Introduction",
          authors: "Gina Wisker",
          publisher: "A&C Black",
            image:'5.jpg',
            pageCount: 294,
            price:150, discount:2, 
            discountPrice:150-2/100 * 150,
           quantity:1, 
            desc:'This is a series of introductory books about different types of writing. One strand of the series focuses on genres such asScience Fiction, Horror, Romance, and Crime, and the other focuses on movements or styles often associated with historicaland cultural locations—Postcolonial, Native American, Scottish, Irish, American Gothic.Authors covered in this volume includeWilliam Peter Blatty, Ira Levine, BramStoker, Shirley Jackson, Angela Carter,Mary Shelley, Stephen King, Anne Rice,and Washington Irving.',
            lang: "en",
            country: "IN",
            categories:  "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=PD1CZfa5wicC&pg=PA159&dq=horror&hl=&cd=6&source=gbs_api",
           },
         {id:6,
            title: "Film, Horror, and the Body Fantastic",
          authors:  "Linda Badley",
          publisher: "Greenwood Publishing Group",
            image:'6.jpg',
            pageCount: 199,
            price:80, discount:2, 
            discountPrice:80-2/100 * 80,
           quantity:1, 
            desc:'Drawing from feminist film theory, psychoanalytic theory, cultural criticism, and gender studies, Badley interprets horror film as a discourse of the body.',
          lang: "en",
            country: "IN",
            categories:  "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=PD1CZfa5wicC&pg=PA159&dq=horror&hl=&cd=6&source=gbs_api",
           },
         {id:7,
            title: "Horror Film",
            subtitle: "Creating and Marketing Fear",
            authors:  "Steffen Hantke",
            
            publisher: "Univ. Press of Mississippi",
            image:'7.jpg',
            pageCount: 261,
            price:140, discount:4, 
            discountPrice:140-4/100 * 140,
           quantity:1, 
            desc:'Essays on the rise of the horror film and on how moviemakers package and promote fright',
            lang: "en",
            country: "IN",
            categories:  "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=ZTOtnZg_j3gC&pg=PA35&dq=horror&hl=&cd=7&source=gbs_api",
           },
         {id:8,
            title: "Horror at the Drive-in",
            subtitle: "Essays in Popular Americana",
        subtitle: "Essays in Popular Americana",
          authors:   "Gary Don Rhodes",
          
          publisher: "McFarland",
            image:'8.jpg',
            pageCount: 306,
            price:180, discount:4, 
            discountPrice:180-4/100 * 180,
           quantity:1, 
            desc:'Drive-in movie theaters and the horror films shown at them during the 1950s, 60s, and early 70s may be somewhat outdated, but they continue to enthrall movie buffs today. More than just fodder for the satirical cannons of Joe Bob Briggs and Mystery Science Theatre 3000, they appeal to knowledgeable fans and film scholars who understand their influence on American popular culture. This book is a collection of eighteen essays by various scholars on the classic drive-in horror film experience. Those in Section One emphasize the roles of the drive-in theater in the United States--and its cultural cousin, Australia. Section Two examines how horror operated at the drive-in, the rhetoric used in coming attraction trailers, horror film premieres at drive-ins, double features, and the preproduction, production, and marketing of Last House on the Left. Section Three addresses the effects of the Vietnam War and counter-culture on The Texas Chainsaw Massacre, and the Cold War on Cat Women of the Moon. Section Four explores gender issues and sexuality, two of the most common and most important subjects of horror film analysis. Section Five covers drive-in culture via Hush...Hush, Sweet Charlotte, 2000 Maniacs, and the films of Mario Bava. Section Six investigates a variety of issues, such as the drive-in horror films embrace of DNA, the use of cinematic form to create a non-Hollywood look in Wizard of Gore, and the many different prints and running times of I Drink Your Blood.' ,
            lang: "en",
            country: "IN",
            categories:  "Performing Arts",
            previewLink: "http://books.google.co.in/books?id=90tpv3Szni0C&pg=PA155&dq=horror&hl=&cd=8&source=gbs_api",
           },
         {id:9,
         title: "Writing Horror and the Body",
          subtitle: "The Fiction of Stephen King, Clive Barker, and Anne Rice",
          authors:  "Linda Badley",
         image:'9.jpg',
         pageCount: 183,
          price:120, 
         discount:3, 
         discountPrice:120-3/100 * 120,
        quantity:1, 
         desc:'Overview of horror literature of Stephen King, Clive Barker and Anne rice',
         lang: "en",
         country: "IN",
         categories:  "Literary Criticism",
         previewLink: "http://books.google.co.in/books?id=iaHQorgoqd4C&pg=PA73&dq=horror&hl=&cd=9&source=gbs_api",
        },
         {id:10, title:'The Biology of Horror ', 
         subtitle: "Gothic Literature and Film", 
         publisher: "SIU Press",
         authors:"Jack Marlon",
         image:'10.jpg', 
         pageCount: 173,
         price:100, discount:3, 
         discountPrice:120-3/100 * 100,
         quantity:1, 
         desc:'Unearthing the fearful flesh and sinful skins at the heart of gothic horror, Jack Morgan rends the genre’s biological core from its oft-discussed psychological elements and argues for a more transhistorical conception of the gothic, one negatively related to comedy. The Biology of Horror: Gothic Literature and Film dissects popular examples from the gothic literary and cinematic canon, exposing the inverted comic paradigm within each text. Morgan’s study begins with an extensive treatment of comedy as theoretically conceived by Suzanne Langer, C. L. Barber, and Mikhail Bakhtin. Then, Morgan analyzes the physical and mythological nature of horror in inverted comic terms, identifying a biologically grounded mythos of horror. Motifs such as sinister loci, languishment, masquerade, and subversion of sensual perception are contextualized here as embedded in an organic reality, resonating with biological motives and consequences. Morgan also devotes a chapter to the migration of the gothic tradition into American horror, emphasizing the body as horror’s essential place in American gothic. The bulk of Morgan’s study is applied to popular gothic literature and films ranging from high gothic classics like Matthew Lewis’s The Monk, Ann Radcliffe’s The Mysteries of Udolpho, Charles Maturin’s Melmoth the Wanderer, and Mary Shelley’s Frankenstein, to later literary works such as Poe’s macabre tales, Melville’s “Benito Cereno,” J.S. Le Fanu’s Uncle Silas, H.P. Lovecraft’s “The Shadow over Innsmouth,” Shirley Jackson’s The Haunting of Hillhouse, Stephen King’s Salem’s Lot, and Clive Barker’s The Damnation Game. Considered films include Nosferatu, Invasion of the Body Snatchers, Friday the 13th, Halloween, Night of the Living Dead, Angel Heart, The Stand, and The Shining. Morgan concludes his physical examination of the Gothic reality with a consideration born of Julia Kristeva’s theoretical rubric which addresses horror’s existential and cultural significance, its lasting fascination, and its uncanny positive—and often therapeutic—direction in literature and film.',
         lang: "en",
         country: "IN",
         categories:  "Literary Criticism",
         previewLink: "http://books.google.co.in/books?id=6lyFWxtoVQQC&pg=PA37&dq=horror&hl=&cd=10&source=gbs_api",
        },

        ],
        product:{}
}

const ProductsHbReducer =(state= initState, action) => {
   switch(action.type){
       case "PRODUCT":
           return{...state, product: state.products.find(product => product.id === parseInt(action.id))}
       default:
           return state;
   }
}

export default ProductsHbReducer;