const initState={
    products:[
        
         {id:52,
            title: "The Poetry of Dante",
            publisher: "Ardent Media",
            authors: "Gordon Brotherston",
            publisher: "Cambridge University Press",
            image:'53.jpg',
            pageCount: 236, 
            price:160, 
            discount:3, 
            discountPrice:160-3/100 * 160,
           quantity:1, 
            desc: "This study considers the ways Spanish American and Brazilian poets differ from their European counterparts by considering 'Latin American' as more than a perfunctory epithet. It sets the orthodox Latin tradition of the subcontinent against others that have survived or grown up after the conquest then pays attention to those poets who, from Independence, have striven to express a specifically American moral and geographical identity. Dr Brotherson focuses on Modernismo, or the 'coming of age' of poetry in Spanish America and Brazil, and the importance of the movements associated with it. He considers César Vallejo and Pablo Neruda, probably the greatest of the selection, Octavio Paz, and modern poets who have reacted differently to the idea that Latin America might now be thought to have not just a geographical but a nascent political identity of its own. Poems are liberally quoted, and treated as entities in their own right.",
            lang: "en",
            country: "IN",
            categories: "Literary Criticism",
            previewLink: "http://books.google.co.in/books?id=MQfU_wQukVIC&printsec=frontcover&dq=peotry&hl=&cd=1&source=gbs_api",
           },
         {id:53,
            title: "Latin American Poetry",
            subtitle: "Origins and Presence",
            authors: "Gordon Brotherston",
            publisher: "Cambridge University Press",
            image:'52.jpg',
            pageCount: 236, 
            price:160, 
            discount:3, 
            discountPrice:160-3/100 * 160,
           quantity:1, 
            desc: "This study considers the ways Spanish American and Brazilian poets differ from their European counterparts by considering 'Latin American' as more than a perfunctory epithet. It sets the orthodox Latin tradition of the subcontinent against others that have survived or grown up after the conquest then pays attention to those poets who, from Independence, have striven to express a specifically American moral and geographical identity. Dr Brotherson focuses on Modernismo, or the 'coming of age' of poetry in Spanish America and Brazil, and the importance of the movements associated with it. He considers César Vallejo and Pablo Neruda, probably the greatest of the selection, Octavio Paz, and modern poets who have reacted differently to the idea that Latin America might now be thought to have not just a geographical but a nascent political identity of its own. Poems are liberally quoted, and treated as entities in their own right.",
            lang: "en",
            country: "IN",
            categories: "Literary Criticism",
            previewLink: "http://books.google.com/books/content?id=Uk47AAAAIAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
           },
         {id:54,
            title: "These My Words",
            subtitle: "The Penguin Book of Indian Poetry",
          publisher: "Penguin UK",
        
            image:'54.jpg',
            pageCount: 476,
            price:460, 
            discount:2, 
            discountPrice:460-2/100 * 460,
           quantity:1, 
            desc:"...Suddenly, he saw something shiny at the bottom of the abyss. He squinted his eyes to see what it was. He ran back to his binoculars and turned them to see what it was. Sharp barbed wires that separated the two mountains came into focus. He had come as far as he could in his country. But she was standing in another country. He was in South India and she was in North India... Have you ever imagined India being divided into two countries? What happens to the millions of Indians who are from South India but are now residing in North India? Kaahi & Jai were two such people who got trapped in this situation. Everything was going smoothly for them and suddenly, their world turned upside down. How will they get together? Will India become one again? Take an exciting journey with them from their college days in Mumbai to their life in the US and back to India when they find out that India is divided. IndiaWasOne.com",
            lang: "en",
            country: "IN",
            categories:  "Poetry",
            previewLink: "http://books.google.co.in/books?id=1Q9mjwEACAAJ&dq=action+and+adventure&hl=&cd=5&source=gbs_api",
           },
      
         {id:55,
            title: "Miscellaneous Poetry",
            authors:  "William Herbert",
            image:'55.jpg',
            pageCount: 88,
            price:40, 
            discount:3, 
            discountPrice:40-3/100 * 40,
           quantity:1, 
            desc:"",  
              lang: "en",
            country: "IN",
            categories:  "English poetry",
            previewLink: "http://books.google.co.in/books?id=LJA3AAAAYAAJ&pg=RA2-PA10&dq=peotry&hl=&cd=4&source=gbs_api",
           },
         {id:56,
          title: "Designed for Reading and Recitation",
          subtitle: "the Whole Selected from the Best Poets in the English Language",
          authors: "Dan Bailey",
          publisher: "Eliza Robbins",
            image:'56.jpg',
            pageCount: 348,
            price:350, discount:2, 
            discountPrice:350-2/100 * 350,
           quantity:1, 
            desc:"",
            lang: "en",
            country: "IN",
            categories:  "American poetry",
            previewLink: "http://books.google.co.in/books?id=bJ0XAAAAYAAJ&pg=PA202&dq=peotry&hl=&cd=5&source=gbs_api",
           },
        
         {id:57,
          title: "Illustrations of Anglo- Saxon Poetry",
          subtitle: "Illustrations of Anglo- Saxon Poetry",
            authors:  "J. J. Conybeare",
            
            publisher: "Nader Elhefnawy",
            image:'57.jpg',
            pageCount: 229,
            price:140, discount:4, 
            discountPrice:140-4/100 * 140,
           quantity:1, 
            desc:""  ,
             lang: "en",
            country: "IN",
            categories:  "PerfLiterary Criticism",
            previewLink: "http://books.google.co.in/books?id=BW4AAAAAcAAJ&pg=PA3&dq=peotry&hl=&cd=6&source=gbs_api",
           },
         {d:58,
          title: "Poetics; Or a Series of Poems and Disquisitions on Poetry ...",
          subtitle: "Poetics",
          authors:   "George Dyer",
            publisher: "Springer",
            image:'58.jpg',
            pageCount: 234,
            price:180, discount:4, 
            discountPrice:120-4/100 * 120,
           quantity:1, 
            desc:"",  
              lang: "en",
            country: "IN",
            categories:  "English poetry",
            previewLink: "http://books.google.co.in/books?id=uiggAAAAMAAJ&pg=PA83&dq=peotry&hl=&cd=7&source=gbs_api",
           },
         {id:59,
          title: "The Complete Art of Poetry",
          subtitle: "In Six Parts",
          publisher: "Lulu Press, Inc",
          authors:  "Charles Gildon",
         image:'59.jpg',
         pageCount: 183,
          price:120, 
         discount:3, 
         discountPrice:120-3/100 * 120,
        quantity:1, 
         desc:"In Six Parts, I. Of the Nature, Use, Excellence, Rise and Progress of Poetry, &c.; II. Of the Use and Necessity of Rules in Poetry; III. Of the Manner, Rules, and Art of Composing Epigrams, Pastorals, Odes, &c.; IV. Of Tragedy and Comedy; how to Draw the Plot, and Form the Characters of Both; V. The Rules of the Epic Or Narrative Poem, of the Poetic Diction Or Language, and of English Numbers; VI. A Collection of the Most Beautiful Descriptions, Similes, Allusions, &c. from Spenser, and Our Best English Poets, as Well Ancient as Modern, with Above Ten Thousand Verses, Not to be Found in Any Performance of this Kind; Shakespeariana, Or the Most Beautiful Topicks, Descriptions, and Similes that Occur Throughout All Shakespear's Plays",
    
         lang: "en",
         country: "IN",
         categories:  "Criticism",
         previewLink: "http://books.google.co.in/books?id=dbgnAAAAMAAJ&pg=PA3&dq=peotry&hl=&cd=8&source=gbs_api",
        },
         {id:60, 
          title: "Concerning Poetry",
          subtitle: "Concerning Poetry",
         publisher: "Hachette UK",
         authors:"Amish Tripathi",
         image:'60.jpg', 
         pageCount: 320,
         price:140, discount:2, 
         discountPrice:140-2/100 * 140,
         quantity:1, 
         desc:"" , 
         lang: "en",
         country: "IN",
         categories:   "American poetry",
         previewLink: "http://books.google.co.in/books?id=2SsrAQAAIAAJ&q=peotry&dq=peotry&hl=&cd=9&source=gbs_api",
        },
        {id:61, 
            title:"The History of English Poetry",
          subtitle: "The History of English Poetry",
         publisher: "",
         authors:"Thomas Warton",
         image:'61.jpg', 
         pageCount: 432,
         price:280, discount:2, 
         discountPrice:280-2/100 * 140,
         quantity:1, 
         desc: "The History of English Poetry from the Close of the 11th Century to the Commencement of the 18th Century, to which are Prefixed Three Dissertations ..., 3",
         lang: "en",
         country: "IN",
         categories:   "Poetry",
         previewLink: "http://books.google.co.in/books?id=XzCDqdhBzaUC&pg=PA395&dq=peotry&hl=&cd=10&source=gbs_api",
        },
        ],
        product:{}
}

const ProductsPoetryReducer =(state= initState, action) => {
   switch(action.type){
       case "PRODUCT":
           return{...state, product: state.products.find(product => product.id === parseInt(action.id))}
       default:
           return state;
   }
}

export default ProductsPoetryReducer;